### PR TITLE
Change apiVersion to zalando.org/v1

### PR DESCRIPTION
**Pull request by mikkeloscar**
This changes the `apiVersion` defined for the `AWSIAMRole` CRD from `amazonaws.com/v1` to `zalando.org/v1`.
This is unfortunately a breaking change that we feel the need to make as we are preparing to roll this out in Zalando.

The reason to make this change is to ensure that Zalando as a company is not breaking any Trademark laws. While this project has been developed by me until now. As I'm an employee of Zalando because of European Copyright laws the copyright of the project falls to Zalando as this is related to my daily work. Therefore it makes sense to use `zalando.org/v1` instead of coming up with another name which may be trademarked by someone else.

@seh already brought up this issue in the original PR.

## Migration steps

1. Apply new CRD:

    ```
    kubectl apply -f docs/aws_iam_role_crd.yaml
    ```

2. Copy old resources to new version:

    ```bash
    #!/bin/bash

    for ns in $(kubectl get ns --no-headers -o "custom-columns=:metadata.name"); do
        for res in $(kubectl --namespace "$ns" get awsiamroles.amazonaws.com --no-headers -o custom-columns=:metadata.name); do
            kubectl --namespace "$ns" get awsiamroles.amazonaws.com "$res" -o json | sed 's#amazonaws.com/v1#zalando.org/v1#' | kubectl apply -f -
        done
    done
    ```

3. Deploy new version of controller `>=0.1.0` (See https://github.com/mikkeloscar/kube-aws-iam-controller#setup).

4. Delete old resources and old CRD:

    ```
    kubectl delete crd awsiamroles.amazonaws.com
    ```

### CODE REVIEW

**Comment by seh** [comment]
Given the version bump, do you have any plans to phase out [the older IAM role binding technique of mounting _Secrets_ named with a special prefix](https://github.com/mikkeloscar/kube-aws-iam-controller/blob/48b2b53b063392c3f9a4cfc5fa57e9ebc929897e/pod_watcher.go#L104-L113
)? I'd prefer to be able to deploy the controller at least with the pod cache disabled. If we can't remove it for fear of breaking existing users, perhaps we could disable it via command-line flag.

I was hoping that the next major version bump would be our chance to remove that feature.

**Comment by mikkeloscar** [comment]
I created #25 to track this. I agree we should phase it out.

**Comment by Shinzu** [comment]
@mikkeloscar if your deployment is with rbac you must also migrate the clusterrole

**Comment by mikkeloscar** [comment]
@Shinzu thanks, added this as a step in the description above!

**Pull request merged**
